server {
    listen 8765;

    root /opt/element-web;
    index index.html;

    location %%INGRESS_ENTRY%% {
        alias /opt/element-web/;
        try_files $uri $uri/ /index.html;

        # Required for Element Web
        add_header X-Frame-Options "ALLOWALL";
        add_header Content-Security-Policy "frame-ancestors *";
    }

    location / {
        try_files $uri $uri/ /index.html;

        add_header X-Frame-Options "ALLOWALL";
        add_header Content-Security-Policy "frame-ancestors *";
    }
}
